### ISSUE TITLE
Deployed VM not being registered with VMware Workstation

### ISSUE THREAD

**Issue by milne1282** [elsudano/terraform-provider-vmworkstation#2]
After successfully provisioning a VM on a local VMware Workstation instance, this instance was not registered with Workstation. The VM was created in the correct location on disk, it was not appearing in the UI.  Running a "Scan for Virtual Machines ..." in the UI was able to correctly find and add the VM to the list.

`terraform {
  required_version = ">= 0.13"
  required_providers {
    vmworkstation = {
      source  = "elsudano/vmworkstation"
      version = "0.1.7"
    }
  }
}

resource "vmworkstation_vm" "test_machine" {
  sourceid     = "VU1FQD96M690MO2Q1QA1MOC6KR8M4PEO"
  denomination = "testVM01"
  description  = "Some Description"
  processors   = "2"
  memory       = "2048"
}
`

Let me know if I can provide any logs, or if you need any other configuration.

Cheers

**Comment by elsudano** [comment]
Sorry I did reply in the another issue.

Basically the problem here is the API REST because don't permit manage the UI of workstation.

To we can manage the VMS in the UI is necessary doing by hand.

Maybe in the next version of the provider of Terraform I will try improve this part, but is difficult because the vmx file have many options to review.

One more time thanks for your time to test the software and I appreciate your comments

**Comment by elsudano** [comment]
hi Milne

It seems that in the VmWare Workstation 16 version the API REST allows registering the VMs within the GUI

I'm preparing a new version for this to be done.

Stay tuned for new releases

Cheers

**Comment by elsudano** [comment]
this issue is repeated
